name:    rentals
version: "0.0.0"

default-extensions:
- OverloadedStrings

dependencies:
- base
- yesod
- yesod-persistent
- yesod-paginator
- yesod-auth
- shakespeare
- blaze-markup
- persistent
- persistent-sqlite
- resourcet
- monad-logger
- bytestring
- data-default
- text
- aeson
- case-insensitive
- mtl
- random
- transformers
- http-types
- network-uri
- extra
- uuid
- wreq
- lens
- iCalendar

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  rentals:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rentals
