port: "_env:PORT:3033"

admin:
  - username: "_env:ADMIN_USERNAME:jappie"
    password: "_env:ADMIN_PASSWORD:jappie"

database:
  user:     "_env:DATABASE_USER:rental"
  password: "_env:DATABASE_PASSWORD:rental"
  host:     "_env:DATABASE_HOST:localhost"
  port:     "_env:DATABASE_PORT:30336"
  database: "_env:DATABASE_NAME:xxxx"
  poolsize: "_env:DATABASE_POOLSIZE:1"

stripe:
  secret: "_env:STRIPE_SECRET:x0"
  public: "_env:STRIPE_PUBLIC:x0"
