port:  "_env:PORT:3033"
email: "_env:EMAIL:info@rental.jappie.me"

admin:
  - username: "_env:ADMIN_USERNAME:jappie"
    password: "_env:ADMIN_PASSWORD:jappie"
    email:    "_env:ADMIN_EMAIL:email"

database:
  user:     "_env:DATABASE_USER:rental"
  password: "_env:DATABASE_PASSWORD:rental"
  host:     "_env:DATABASE_HOST:localhost"
  port:     "_env:DATABASE_PORT:5432"
  database: "_env:DATABASE_NAME:rental"
  poolsize: "_env:DATABASE_POOLSIZE:1"
  migration_folder: "_env:MIGRATION_FOLDER:migrations/up"

smtp:
  password: "_env:SMTP_PASSWORD:x0"
  login:    "_env:SMTP_LOGIN:x0"
  host:     "_env:SMTP_HOST:localhost"
  port:     "_env:SMTP_PORT:587"

stripe:
  secret: "_env:STRIPE_SECRET:x0"
  public: "_env:STRIPE_PUBLIC:x0"
